[tox]
envlist=py{310,311,312,313,314,315},lint,check-docs

[testenv]
extras =
    dev
    todoist
    evernote
    onenote
allowlist_externals = make
commands = make test
; Fix coverage not working because tox doesn't install
; sources to the working dir by default.
usedevelop = True

[gh-actions]
python =
    3.10: py310
    3.11: py311
    3.12: py312
    3.13: py313
    3.14: py314
    3.15: py315

[testenv:lint]
basepython = python3
; Use `pip install -e .` so isort would treat imports from this package
; as first party imports instead of third party:
usedevelop = True
commands = make lint

[testenv:check-docs]
basepython = python3
commands = make check-docs
