import datetime
import os
from contextlib import ExitStack
from pathlib import Path

import pytest
import pytz

from synctogit.evernote.models import Note, NoteMetadata
from synctogit.evernote.stored_note import EvernoteStoredNote
from synctogit.filename_sanitizer import normalize_filename
from synctogit.service.notes.stored_note import CorruptedNoteError


@pytest.fixture
def note_html():
    return (
        "<!doctype html>\n"
        "<!-- PLEASE DO NOT EDIT THIS FILE -->\n"
        "<!-- All changes you've done here will be stashed on next sync -->\n"
        "<!--+++++++++++++-->\n"
        "<!-- guid: eaaaaaae-1797-4b92-ad11-f3f6e7ada8d7 -->\n"
        "<!-- updateSequenceNum: 12345 -->\n"
        "<!-- title: раз два три название -->\n"
        "<!-- created: 2018-07-11 18:10:40+03:00 -->\n"
        "<!-- updated: 2018-09-23 22:33:10+03:00 -->\n"
        "<!----------------->\n"
        "<html>\n"
        "<head>\n"
    )


@pytest.fixture
def note_header_vars():
    return {
        "guid": "eaaaaaae-1797-4b92-ad11-f3f6e7ada8d7",
        "updateSequenceNum": "12345",
        "title": "раз два три название",
        "created": "2018-07-11 18:10:40+03:00",
        "updated": "2018-09-23 22:33:10+03:00",
    }


def test_note_to_html_valid():
    timezone_input = pytz.timezone("Europe/Moscow")
    timezone_output = pytz.timezone("Asia/Novosibirsk")
    note = Note(
        title="раз два",
        update_sequence_num=12345,
        guid="eaaaaaae-1797-4b92-ad11-f3f6e7ada8d7",
        updated=timezone_input.localize(datetime.datetime(2018, 9, 27, 1, 14, 3)),
        created=timezone_input.localize(datetime.datetime(2018, 9, 27, 1, 14, 3)),
        html="<html><head></head><body>три четыре</body></html>".encode(),
        resources={},
    )
    expected_html = (
        "<!doctype html>\n"
        "<!-- PLEASE DO NOT EDIT THIS FILE -->\n"
        "<!-- All changes you've done here will be stashed on next sync -->\n"
        "<!--+++++++++++++-->\n"
        "<!-- guid: eaaaaaae-1797-4b92-ad11-f3f6e7ada8d7 -->\n"
        "<!-- updateSequenceNum: 12345 -->\n"
        "<!-- title: раз два -->\n"
        "<!-- created: 2018-09-27 05:14:03+07:00 -->\n"
        "<!-- updated: 2018-09-27 05:14:03+07:00 -->\n"
        "<!----------------->\n"
        "<html><head></head><body>три четыре</body></html>"
    )

    html = EvernoteStoredNote.note_to_html(note, timezone_output)
    assert html.decode() == expected_html


def test_get_stored_note_metadata_valid(temp_dir, note_html, note_header_vars):
    notes_dir = Path(temp_dir)

    note = notes_dir / normalize_filename("Eleven ✨") / "Haircut" / "s1.html"
    os.makedirs(str(note.parents[0]))
    note.write_text(note_html)

    guid, metadata = EvernoteStoredNote.get_stored_note_metadata(notes_dir, note)
    assert guid == note_header_vars["guid"]
    assert metadata == NoteMetadata(
        dir=("Eleven _2728", "Haircut"),
        name=("Eleven ✨", "Haircut", note_header_vars["title"]),
        update_sequence_num=int(note_header_vars["updateSequenceNum"]),
        file="s1.html",
    )


@pytest.mark.parametrize(
    "is_valid, parts",
    [
        # fmt: off
        (False, []),
        (True, ["a"]),
        (True, ["a", "b"]),
        (False, ["a", "b", "c"]),
        # fmt: on
    ],
)
def test_get_stored_note_metadata_dir_parts(
    temp_dir, note_html, note_header_vars, is_valid, parts
):
    notes_dir = Path(temp_dir) / "a"
    note = notes_dir.joinpath(*parts) / "s1.html"
    os.makedirs(str(note.parents[0]))
    note.write_text(note_html)

    with ExitStack() as stack:
        if not is_valid:
            stack.enter_context(pytest.raises(CorruptedNoteError))
        EvernoteStoredNote.get_stored_note_metadata(notes_dir, note)


@pytest.mark.parametrize(
    "note_html",
    [
        (
            # Missing title
            "<!doctype html>\n"
            "<!-- PLEASE DO NOT EDIT THIS FILE -->\n"
            "<!-- All changes you've done here will be stashed on next sync -->\n"
            "<!--+++++++++++++-->\n"
            "<!-- guid: eaaaaaae-1797-4b92-ad11-f3f6e7ada8d7 -->\n"
            "<!-- updateSequenceNum: 12345 -->\n"
            "<!-- created: 2018-07-11 18:10:40+03:00 -->\n"
            "<!-- updated: 2018-09-23 22:33:10+03:00 -->\n"
            "<!----------------->\n"
            "<html>\n"
        ),
        (
            # Missing guid
            "<!doctype html>\n"
            "<!-- PLEASE DO NOT EDIT THIS FILE -->\n"
            "<!-- All changes you've done here will be stashed on next sync -->\n"
            "<!--+++++++++++++-->\n"
            "<!-- title: раз два три название -->\n"
            "<!-- updateSequenceNum: 12345 -->\n"
            "<!-- created: 2018-07-11 18:10:40+03:00 -->\n"
            "<!-- updated: 2018-09-23 22:33:10+03:00 -->\n"
            "<!----------------->\n"
            "<html>\n"
        ),
        (
            # Non-numeric updateSequenceNum
            "<!doctype html>\n"
            "<!-- PLEASE DO NOT EDIT THIS FILE -->\n"
            "<!-- All changes you've done here will be stashed on next sync -->\n"
            "<!--+++++++++++++-->\n"
            "<!-- guid: eaaaaaae-1797-4b92-ad11-f3f6e7ada8d7 -->\n"
            "<!-- title: раз два три название -->\n"
            "<!-- updateSequenceNum: 123haha -->\n"
            "<!-- created: 2018-07-11 18:10:40+03:00 -->\n"
            "<!-- updated: 2018-09-23 22:33:10+03:00 -->\n"
            "<!----------------->\n"
            "<html>\n"
            "<head>\n"
        ),
    ],
)
def test_get_stored_note_metadata_invalid_vars(temp_dir, note_html, note_header_vars):
    notes_dir = Path(temp_dir)
    note = notes_dir / "Eleven" / "Haircut" / "s1.html"
    os.makedirs(str(note.parents[0]))
    note.write_text(note_html)

    with pytest.raises(CorruptedNoteError):
        EvernoteStoredNote.get_stored_note_metadata(notes_dir, note)
